from flask import Flask, render_template, request
import os 
import numpy as np
import pandas as pd
from mlProject.config.configuration import ConfigurationManager
from mlProject.components.prediction_new_data import PredictionNewDataPipeline
from mlProject import logger


# index.html and results.html are templates generated by the website (Bootstrap)

# initialize a flask app
app = Flask(__name__) 


# route to display the home page
@app.route('/',methods=['GET'])  
def homePage():
    return render_template("index.html")

# route to train the pipeline
@app.route('/train',methods=['GET'])  
def training():
    os.system("python main.py")
    return "Training Successful!"  # do the training using the web : "http://127.0.0.1:8080/train" => output sur page web "Training Successful!"


# route to show the predictions in a web UI
@app.route('/predict',methods=['POST','GET'])
def index():
    if request.method == 'POST': # POST: used to send data to the server
                                 # Usage: HTML forms, login/password submission, sending features to an ML model
        try:
            #  reading the inputs given by the user (from web)
            area = float(request.form['area'])
            bedrooms = int(request.form['bedrooms'])
            bathrooms = int(request.form['bathrooms'])
            stories = int(request.form['stories'])
            
            mainroad = str(request.form['mainroad']) 
            guestroom = str(request.form['guestroom']) 
            basement = str(request.form['basement'])   
            hotwaterheating = str(request.form['hotwaterheating'])   
            
            airconditioning = str(request.form['airconditioning'])     
            parking = int(request.form['parking'])    
            prefarea = str(request.form['prefarea'])   
            furnishingstatus = str(request.form['furnishingstatus'])           

            data = [area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus]
            
            #data = np.array(data).reshape(1, 12)
            
            config = ConfigurationManager()   
            pred_new_data_config = config.get_prediction_new_data_config()
            pred_new_data = PredictionNewDataPipeline (config = pred_new_data_config)
            data_normalized = pred_new_data.Normalize_input_data (data)
            predict = pred_new_data.predict(data_normalized)

            return render_template('results.html', prediction = str(predict))

        except Exception as e:
            print('The Exception message is: ', e)
            return 'something is wrong'

    else: # GET: used to retrieve data from the server
          # Usage: displaying a page, retrieving information, simple searches
        return render_template('index.html')


if __name__ == "__main__":
	# app.run(host="0.0.0.0", port = 8080, debug=True)
	app.run(host="0.0.0.0", port = 8080)