from mlProject import logger
from mlProject.pipeline.stage_01_data_ingestion import DataIngestionTrainingPipeline_main
from mlProject.pipeline.stage_02_data_validation import DataValidationTrainingPipeline_main
from mlProject.pipeline.stage_03_data_transformation import DataValidationTransformationPipeline_main


#logger.info("welcome")

DataIngestionTrainingPipeline_main()

DataValidationTrainingPipeline_main()

DataValidationTransformationPipeline_main()